{ config, lib, pkgs, ... }:

let
  # matugen reads its own TOML and cannot expand $dir the way set.sh does, so
  # input_path has to be an absolute store path -- which is not known until
  # this derivation is being built. That is why this one file is generated
  # rather than forked. Note the two lines point opposite ways on purpose:
  # the template is source and lives in the store, the output is state.
  quickshellConfig = pkgs.runCommand "quickshell-config" { } ''
    cp -r ${./../quickshell} "$out"
    chmod -R u+w "$out"

    cat > "$out/theme-switcher/wallpaper-theme/matugen/config.toml" <<EOF
    # Generated by home/quickshell.nix. See that file for why.
    [config]

    [templates.quickshell]
    input_path = '$out/theme-switcher/wallpaper-theme/matugen/template.json'
    output_path = '~/.local/state/quickshell/theme-switcher/wallpaper-theme.json'
    EOF
  '';
in
{
  options.calango.quickshellConfig = lib.mkOption {
    type = lib.types.package;
    readOnly = true;
    description = "The quickshell config tree, in the store.";
  };

  config.calango.quickshellConfig = quickshellConfig;
}
