# The one place that knows how to turn a declaration into a Debian package.
#
# A plain Nix function, NOT a Home Manager module -- the same shape and for the
# same reason as lib/nixgl.nix: flake.nix lists its modules one by one, so a
# file absent from that list is visibly not one.
#
# Two exports, and they are separate because of how each is TESTED. `build`
# produces an artifact an agent can inspect with dpkg-deb. `driftCheck`
# produces a script an agent can RUN. The comparison deliberately does not live
# inline in the activation hook: the activation script only runs under
# DRY_RUN=1 for anyone but the user, and DRY_RUN=1 makes `run` echo its
# argument instead of executing it -- so an inline body could never be executed
# by an implementer or a reviewer, and a guard nobody can run is a guard nobody
# can prove able to fail. This project has shipped three of those.
{ pkgs }:

let
  inherit (pkgs) lib;

  # Debian relationship fields are comma-separated. Sorted so the control file
  # is a function of the SET, not of attribute insertion order -- Nix already
  # stores attrsets sorted, but saying so here keeps the property local.
  field = name: names:
    lib.optionalString (names != [ ])
      "${name}: ${lib.concatStringsSep ", " (lib.sort (a: b: a < b) names)}\n";

  # A Debian extended description: every line prefixed with one space, and an
  # empty line spelled " .". A reason written as a multi-line Nix string would
  # otherwise inject a bare newline and truncate the field, so flatten first.
  descLine = s:
    " " + lib.concatStringsSep " "
      (lib.filter (x: x != "" ) (lib.splitString " "
        (lib.replaceStrings [ "\n" "\t" ] [ " " " " ] s)));

  reasonLines = attrs:
    lib.concatStringsSep "\n"
      (lib.mapAttrsToList (n: why: descLine " * ${n}: ${why}") attrs);

  # Built by concatenation, the same idiom home/default.nix uses for the nixgl
  # needle. Written into the indented string directly this needs
  # `'''${db:Status-Abbrev}'` -- correct, unreadable, and exactly the kind of
  # thing a later editor "fixes" into a format string that silently returns
  # empty for every package.
  statusFmt = "$" + "{db:Status-Abbrev}";
in
{
  build =
    { manifest, manifestFile, version }:
    let
      control = ''
        Package: calango-desktop
        Version: ${version}
        Architecture: all
        Maintainer: Igor Sutton <igor.sutton@calangotech.eu>
        Section: metapackages
        Priority: optional
      ''
      + field "Depends" (builtins.attrNames manifest.keep)
      + field "Conflicts" (builtins.attrNames manifest.ban)
      + ''
        Description: calango-nix glue for the Debian side
         Declares the Debian packages this machine must keep, the ones it must
         not have, and the files and ufw profiles the Nix side needs Debian to
         own. Generated by calango-nix; do not edit by hand.
         .
         Depends is not decoration. It is what replaces `apt-mark manual` for
         these packages: a dependency of a manually-installed package cannot be
         taken by autoremove, and unlike a mark it carries its reason.
         .
         Kept:
        ${reasonLines manifest.keep}
         .
         Refused, because the Nix side owns them now:
        ${reasonLines manifest.ban}
      '';

      # Only /etc entries may be conffiles, per Debian policy. The ufw profiles
      # are the only /etc payload this package has.
      conffiles =
        lib.concatMapStrings (n: "/etc/ufw/applications.d/${n}\n")
          (builtins.attrNames manifest.ufwProfiles);
    in
    pkgs.runCommand "calango-desktop-${version}"
      {
        inherit control conffiles;
        passAsFile = [ "control" "conffiles" ];
        nativeBuildInputs = [ pkgs.dpkg ];
      }
      ''
        mkdir -p pkg/DEBIAN pkg/usr/share/calango-desktop
        cp "$controlPath" pkg/DEBIAN/control
        cp ${manifestFile} pkg/usr/share/calango-desktop/manifest.json

        ${lib.optionalString (manifest.ufwProfiles != { }) ''
          mkdir -p pkg/etc/ufw/applications.d
          cp "$conffilesPath" pkg/DEBIAN/conffiles
        ''}
        ${lib.concatStrings (lib.mapAttrsToList (n: body: ''
          cp ${pkgs.writeText "ufw-profile-${n}" body} pkg/etc/ufw/applications.d/${n}
        '') manifest.ufwProfiles)}

        ${lib.concatStrings (lib.mapAttrsToList (path: body: ''
          mkdir -p "pkg/$(dirname ${path})"
          cp ${pkgs.writeText "debfile-${baseNameOf path}" body} "pkg/${path}"
        '') manifest.files)}

        # Reproducibility. Nix's stdenv sets SOURCE_DATE_EPOCH to 315532800
        # (1980-01-01 UTC), so every file gets that timestamp instead of its
        # real mtime, and the archive is a function of content alone.
        # dpkg-deb itself clamps nothing -- it writes whatever mtime the tar
        # member already has. Proven by `nix build --rebuild`, which is step
        # 4 of this task.
        #
        # chmod BEFORE touch: `cp` out of the store leaves files mode 444, and
        # the permission bits go into the archive exactly as they are here.
        chmod -R u+w,go-w pkg
        find pkg -exec touch -h -d @''${SOURCE_DATE_EPOCH:-0} {} +

        # $out is a DIRECTORY, not the file. apt needs a path ending in .deb
        # with a package-shaped name; a bare-file output gives ./result, which
        # `apt install` rejects.
        mkdir -p "$out"
        dpkg-deb --root-owner-group -Zxz --build pkg \
          "$out/calango-desktop_${version}_all.deb"
      '';

  driftCheck =
    { manifestFile, banned }:
    pkgs.writeShellScript "calango-deb-drift" ''
      want=${manifestFile}
      installed="''${1:-/usr/share/calango-desktop/manifest.json}"

      # Three outcomes, not two. A missing file makes `cmp` fail, so a check
      # that only asked "did cmp succeed" would report a package that was NEVER
      # INSTALLED identically to one that is merely stale. CLAUDE.md: a check
      # for a file's absence proves nothing unless you know every state the
      # file could be in. Spec 15 shipped exactly that mistake.
      if [ ! -e "$installed" ]; then
        echo "apt: calango-desktop is not installed." >&2
        echo "  The keep set is held only by apt-mark flags, and the ufw" >&2
        echo "  profiles and session entry this flake declares are absent." >&2
        echo "    sg nix-users -c 'nix build .#calangoDeb'" >&2
        echo "    sudo apt install ./result/calango-desktop_*_all.deb" >&2
      elif ! cmp -s "$installed" "$want"; then
        echo "apt: calango-desktop is out of date." >&2
        echo "  The declaration in this flake differs from the one the" >&2
        echo "  installed package was built from." >&2
        echo "    sg nix-users -c 'nix build .#calangoDeb'" >&2
        echo "    sudo apt install ./result/calango-desktop_*_all.deb" >&2
      fi

      # A banned package that is installed blocks the install outright, via
      # Conflicts. Report it here rather than letting apt be the first to say
      # so, because at that point the message names the metapackage and not
      # the thing that is actually wrong.
      for p in ${lib.concatStringsSep " " banned}; do
        if [ "$(dpkg-query -W -f='${statusFmt}' "$p" 2>/dev/null)" = "ii " ]; then
          echo "apt: $p is installed and this flake declares it banned." >&2
          echo "  calango-desktop Conflicts with it, so apt will refuse to" >&2
          echo "  install the metapackage until it is removed." >&2
        fi
      done

      exit 0
    '';
}
